server.port=8060
server.address=${SERVER_ADDRESS:0.0.0.0}
server.host=${SERVER_HOST:http://localhost:8060/}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/short_url?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.password=${SPRING_REDIS_PASSWORD:}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.redis.database=${SPRING_REDIS_DATABASE:1}
spring.redis.timeout=${SPRING_REDIS_TIMEOUT:10000ms}

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.root=info
logging.level.cn.itzixiao.short.url=debug
logging.file.name=./log/short-url
